In [13]:
#Array elements only filled only with zero
#function used = np.zeros()

import numpy as np
ar_zero=np.zeros(4)

ar_zero1= np.zeros((3,4))

print("This is a 1D array of elements consisting of only 0 value: ")
print(ar_zero)
print()
print(ar_zero1)
print()
print()


#Array elements only filled only with one
#function used = np.ones()

ar_one=np.ones(4)

print("This is a 1D array of elements consisting of only 0 value: ")
print(ar_one)
print()
print()

#Creating an Empty Array
#function used = np.empty()

ar_em=np.empty(4)

print("This is an empty Array it will display by default the number previously stored in the RAM: ")
print(ar_em)
print()
print()



#Creating an array with a range of elements
#function used = np.arange

ar_rn=np.arange(4)

print(ar_rn)
print()
print()


#Creating an array which is like identity matrix
#function used = np.eye

ar_dia=np.eye(11)
print(ar_dia)
print()
print()


#Creating an array with values spaced randomly
#function used = np.linspace

ar_lin=np.linspace(0,10,num=4)
print(ar_lin)

This is a 1D array of elements consisting of only 0 value: 
[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


This is a 1D array of elements consisting of only 0 value: 
[1. 1. 1. 1.]


This is an empty Array it will display by default the number previously stored in the RAM: 
[1. 1. 1. 1.]


[0 1 2 3]


[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


[ 0.          3.33333333  6.66666667 10.        ]


In [17]:
#To create NumPY arrays with Random functions
# 1. rand() => generate random values between 0-1 => function used: np.random.rand()
# 2. randn() => generated random values close to zero(can also contain neg. values) => function used: np.random.randn()
# 3. randf() => generates float values including zero and smaller that 1 => [0.0, 1.0) => function used: np.random.randf()
# 4. randint() => generates any random values => (min, max, total_values) => function used: np.random.randint(min,max,total_values)

import numpy as np

var=np.random.rand(4)

print(var)
print()

var1=np.random.rand(2,3)

print(var1)
print()
print()

var2=np.random.randn(5)

print(var2)
print()
print()

var3=np.random.ranf(6)

print(var3)
print()
print()

var4=np.random.randint(6,8,10)

print(var4)
print()
print()

[0.84281435 0.30496094 0.04823018 0.95636011]

[[0.60305671 0.49263923 0.97457566]
 [0.75708988 0.29716119 0.92656063]]


[-2.3090098   0.21376595  0.50253693 -0.40359042 -0.58724444]


[0.53643022 0.50686281 0.87786016 0.53940516 0.53486595 0.44568696]


[6 7 7 6 7 7 6 7 7 6]


