In [11]:
#Arrays in NUMpy

import numpy as np

x= [1,2,3,4]

y= np.array([1,2,3,4,5,6,7,8,9,0])

print(y)
print(type(y))

[1 2 3 4 5 6 7 8 9 0]
<class 'numpy.ndarray'>


In [13]:
#To take Input fron the user
L = []

for i in range(1,5):
  int_1= int(input("enter : "))
  L.append(int_1)

print(np.array(L))

enter : 45
enter : 56
enter : 78
enter : 89
[45 56 78 89]


In [22]:
#creating a two dimentional array

ar2= np.array([[1,2,3,4],[5,6,7,8]])

print("Below is a two dimentional array: ")
print(ar2)
print(ar2.ndim)

#creating a three dimentional array

ar3= np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])

print("Below is a three dimentional array: ")
print(ar3)
print(ar3.ndim)

#creating a Multidimentional array

arn= np.array([1,2,3,4,5,6,7,8,9,0],ndmin=23 )

print("Below is a Multi-dimentional array: ")
print(arn)
print(arn.ndim)


Below is a two dimentional array: 
[[1 2 3 4]
 [5 6 7 8]]
2
Below is a three dimentional array: 
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
3
Below is a Multi-dimentional array: 
[[[[[[[[[[[[[[[[[[[[[[[1 2 3 4 5 6 7 8 9 0]]]]]]]]]]]]]]]]]]]]]]]
23
